create table catalogo.TARJETA_CREDITO (
 TARJETA_ID varchar(15) not null PRIMARY KEY,
 TARJETA_EMISOR varchar(100) null,
 TARJETA_FECHA_VENCIMIENTO datetime null,
 TARJETA_CODIGO_SEGURIDAD int null,
 TARJETA_MONTO numeric(8,2) null,
)
ON BDD_BOOKSTORE_CAT;
Go

CREATE TRIGGER [ventas].[ACTUALIZAR_TARJETA]
ON [ventas].[VENTA]
FOR INSERT
AS
BEGIN
    UPDATE ventas.TARJETA_CREDITO set TARJETA_MONTO = (select SUM(MontoTotal) from ventas.VENTA where TARJETA_ID = (
    select TARJETA_ID from inserted))
    where TARJETA_ID = (SELECT TARJETA_ID FROM INSERTED)
END

GO
ALTER TABLE ventas.VENTA
ADD TARJETA_ID VARCHAR(15)
FOREIGN KEY (TARJETA_ID) REFERENCES TARJETA_CREDITO(TARJETA_ID)
GO
 
CREATE TABLE ventas.CLIENTE_TARJETA_CREDITO(
    TARJETA_ID VARCHAR(15) NOT NULL,
    CLIENTE_CEDULA VARCHAR(15) NOT NULL
    FOREIGN KEY (TARJETA_ID) REFERENCES ventas.TARJETA_CREDITO(TARJETA_ID),
    FOREIGN KEY (CLIENTE_CEDULA) REFERENCES catalogo.CLIENTE(CLIENTE_CEDULA)
)
