delete from catalogo.LIBRO
select * from catalogo.LIBRO

---500---

insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (1, 'LightInTheBox Holding Co., Ltd.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (2, 'IZEA Inc.', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (3, 'Republic Services, Inc.', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (4, 'MGM Growth Properties LLC', 'Guaraní');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (5, 'Severn Bancorp Inc', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (6, 'AGNC Investment Corp.', 'Guaraní');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (7, 'Crocs, Inc.', 'Tsonga');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (8, 'Triton International Limited', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (9, 'Nuveen All Cap Energy MLP Opportunities Fund', 'French');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (10, 'Spark Therapeutics, Inc.', 'Chinese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (11, 'Silvercrest Asset Management Group Inc.', 'Punjabi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (12, 'Cementos Pacasmayo S.A.A.', 'Papiamento');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (13, 'Cohen & Steers Closed-End Opportunity Fund, Inc.', 'Dari');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (14, 'Voya Global Equity Dividend and Premium Opportunity Fund', 'Dari');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (15, 'Illumina, Inc.', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (16, 'eHi Car Services Limited', 'Punjabi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (17, 'PJT Partners Inc.', 'Kashmiri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (18, 'Morgan Stanley Asia-Pacific Fund, Inc.', 'French');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (19, 'Pacific Premier Bancorp Inc', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (20, 'National Storage Affiliates Trust', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (21, 'FinTech Acquisition Corp. II', 'Polish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (22, 'AAON, Inc.', 'Bulgarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (23, 'Nova Measuring Instruments Ltd.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (24, 'Hoegh LNG Partners LP', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (25, 'The Priceline Group Inc. ', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (26, 'SeaSpine Holdings Corporation', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (27, 'Summit Hotel Properties, Inc.', 'Guaraní');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (28, 'Hanesbrands Inc.', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (29, 'LaSalle Hotel Properties', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (30, 'AMERISAFE, Inc.', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (31, 'Uni-Pixel, Inc.', 'Italian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (32, 'Harte-Hanks, Inc.', 'Kannada');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (33, 'CSRA Inc.', 'Lao');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (34, 'Clovis Oncology, Inc.', 'Hebrew');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (35, 'Knoll, Inc.', 'Italian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (36, 'Veritiv Corporation', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (37, 'Ita? CorpBanca', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (38, 'Aethlon Medical, Inc.', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (39, 'Systemax Inc.', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (40, 'Silicom Ltd', 'Aymara');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (41, 'Fidelity Southern Corporation', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (42, 'Gabelli Equity Trust, Inc. (The)', 'English');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (43, 'AquaVenture Holdings Limited', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (44, 'New Oriental Education & Technology Group, Inc.', 'West Frisian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (45, 'Partner Communications Company Ltd.', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (46, 'Planet Fitness, Inc.', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (47, 'Five Oaks Investment Corp.', 'Czech');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (48, 'Bioverativ Inc.', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (49, 'Sterling Construction Company Inc', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (50, 'Wins Finance Holdings Inc.', 'Māori');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (51, 'RadNet, Inc.', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (52, 'Argo Group International Holdings, Ltd.', 'Kurdish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (53, 'Columbia Banking System, Inc.', 'Hebrew');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (54, 'First Hawaiian, Inc.', 'Tswana');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (55, 'Rocket Fuel Inc.', 'Punjabi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (56, 'CONMED Corporation', 'English');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (57, 'OceanFirst Financial Corp.', 'Tsonga');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (58, 'First Trust Managed Municipal ETF', 'Estonian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (59, 'Tiffany & Co.', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (60, 'Textainer Group Holdings Limited', 'Punjabi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (61, 'Legg Mason, Inc.', 'Oriya');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (62, 'Markel Corporation', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (63, 'Cytori Therapeutics Inc', 'Indonesian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (64, 'aTyr Pharma, Inc.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (65, 'WisdomTree Emerging Markets Consumer Growth Fund', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (66, 'USA Compression Partners, LP', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (67, 'Poage Bankshares, Inc.', 'Kashmiri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (68, 'Amphastar Pharmaceuticals, Inc.', 'West Frisian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (69, 'Veritex Holdings, Inc.', 'Somali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (70, 'Federal Realty Investment Trust', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (71, 'Baozun Inc.', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (72, 'Hollysys Automation Technologies, Ltd.', 'Guaraní');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (73, 'Civeo Corporation', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (74, 'ClearBridge All Cap Growth ETF', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (75, 'Western Asset/Claymore U.S. Treasury Inflation Prot Secs Fd', 'Croatian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (76, 'Blackrock MuniVest Fund II, Inc.', 'Kyrgyz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (77, 'Savara, Inc.', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (78, 'Conduent Incorporated', 'Dari');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (79, 'MTS Systems Corporation', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (80, 'ReWalk Robotics Ltd', 'Lithuanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (81, 'Champions Oncology, Inc.', 'Romanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (82, 'Thermo Fisher Scientific Inc', 'Swati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (83, 'Capital Bank Financial Corp.', 'Catalan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (84, 'American Water Works', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (85, 'THL Credit, Inc.', 'Kazakh');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (86, 'Barington/Hilco Acquisition Corp.', 'Malagasy');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (87, 'Saia, Inc.', 'Tok Pisin');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (88, 'Jensyn Acquistion Corp.', 'Malayalam');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (89, 'IBERIABANK Corporation', 'Luxembourgish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (90, 'The Organics ETF', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (91, 'LivaNova PLC', 'Tswana');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (92, 'First Trust NASDAQ-100- Technology Index Fund', 'Icelandic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (93, 'China Mobile (Hong Kong) Ltd.', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (94, 'New Relic, Inc.', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (95, 'Buckle, Inc. (The)', 'Aymara');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (96, 'Curtiss-Wright Corporation', 'Persian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (97, 'PRA Health Sciences, Inc.', 'Chinese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (98, 'Southwestern Energy Company', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (99, 'Cathay General Bancorp', 'Malagasy');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (100, 'Regional Management Corp.', 'Malayalam');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (101, 'SemiLEDS Corporation', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (102, 'Cisco Systems, Inc.', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (103, 'STRATS Trust', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (104, 'Acacia Communications, Inc.', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (105, 'OM Asset Management plc', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (106, 'Stericycle, Inc.', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (107, 'New York Community Bancorp, Inc.', 'Tswana');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (108, 'Leju Holdings Limited', 'West Frisian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (109, 'First Guaranty Bancshares, Inc.', 'Malayalam');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (110, 'China Unicom (Hong Kong) Ltd', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (111, 'Piedmont Office Realty Trust, Inc.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (112, 'PGT Innovations, Inc.', 'English');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (113, 'Glatfelter', 'Haitian Creole');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (114, 'CommerceHub, Inc.', 'Hiri Motu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (115, 'Booz Allen Hamilton Holding Corporation', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (116, 'II-VI Incorporated', 'Kannada');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (117, 'C.R. Bard, Inc.', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (118, 'Blackrock MuniYield New York Quality Fund, Inc.', 'Montenegrin');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (119, 'Itron, Inc.', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (120, 'Federated Premier Municipal Income Fund', 'Lithuanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (121, 'Ternium S.A.', 'Khmer');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (122, 'Quotient Limited', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (123, 'MDC Partners Inc.', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (124, 'B.O.S. Better Online Solutions', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (125, 'Wells Fargo & Company', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (126, 'Westpac Banking Corporation', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (127, 'Ekso Bionics Holdings, Inc.', 'Azeri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (128, 'Cerus Corporation', 'Hebrew');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (129, 'MutualFirst Financial Inc.', 'Tsonga');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (130, 'Fiat Chrysler Automobiles N.V.', 'Croatian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (131, 'Franklin Resources, Inc.', 'Finnish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (132, 'Haverty Furniture Companies, Inc.', 'Greek');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (133, 'Pilgrim''s Pride Corporation', 'Guaraní');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (134, 'Landmark Infrastructure Partners LP', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (135, 'Dime Community Bancshares, Inc.', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (136, 'LaSalle Hotel Properties', 'Irish Gaelic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (137, 'Chegg, Inc.', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (138, 'Regional Management Corp.', 'Malay');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (139, 'Tesoro Logistics LP', 'Lao');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (140, 'International Seaways, Inc.', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (141, 'Redhill Biopharma Ltd.', 'Kashmiri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (142, 'Ionis Pharmaceuticals, Inc.', 'Korean');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (143, 'AppFolio, Inc.', 'Polish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (144, 'Soligenix, Inc.', 'French');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (145, 'PAVmed Inc.', 'Kazakh');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (146, 'AquaBounty Technologies, Inc.', 'Tsonga');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (147, 'Kornit Digital Ltd.', 'Yiddish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (148, 'First Trust Large Cap Core AlphaDEX Fund', 'Fijian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (149, 'Tonix Pharmaceuticals Holding Corp.', 'Swahili');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (150, 'Coach, Inc.', 'Danish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (151, 'DCT Industrial Trust Inc', 'Kyrgyz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (152, 'Argo Group International Holdings, Ltd.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (153, 'Landcadia Holdings, Inc.', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (154, 'VictoryShares US EQ Income Enhanced Volatility Wtd ETF', 'Maltese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (155, 'Boardwalk Pipeline Partners L.P.', 'Bislama');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (156, 'Mota Group, Inc.', 'Lao');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (157, 'Biolase, Inc.', 'Guaraní');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (158, 'J & J Snack Foods Corp.', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (159, 'Cadiz, Inc.', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (160, 'Mannatech, Incorporated', 'French');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (161, 'Shineco, Inc.', 'Haitian Creole');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (162, 'HDFC Bank Limited', 'Luxembourgish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (163, 'CBL & Associates Properties, Inc.', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (164, 'Data I/O Corporation', 'Tok Pisin');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (165, 'Immunomedics, Inc.', 'Kurdish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (166, 'Tandy Leather Factory, Inc.', 'Lithuanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (167, 'Editas Medicine, Inc.', 'Chinese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (168, 'Tile Shop Hldgs, Inc.', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (169, 'Addus HomeCare Corporation', 'Kyrgyz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (170, 'Addus HomeCare Corporation', 'Hindi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (171, 'Flushing Financial Corporation', 'Māori');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (172, 'Carolina Trust BancShares, Inc.', 'Lithuanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (173, 'Immune Design Corp.', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (174, 'NASDAQ TEST STOCK', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (175, 'Emmis Communications Corporation', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (176, 'FORM Holdings Corp.', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (177, 'Discover Financial Services', 'Dutch');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (178, 'Etsy, Inc.', 'Kazakh');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (179, 'Cars.com Inc.', 'Quechua');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (180, 'Knowles Corporation', 'Finnish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (181, 'Equifax, Inc.', 'Dari');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (182, 'Deutsche Bank AG', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (183, 'CIM Commercial Trust Corporation', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (184, 'Immune Pharmaceuticals Inc.', 'Montenegrin');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (185, 'Korn/Ferry International', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (186, 'Physicians Realty Trust', 'Tok Pisin');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (187, 'FormFactor, Inc.', 'Tamil');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (188, 'First American Corporation (The)', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (189, 'Cirrus Logic, Inc.', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (190, 'Nuveen Municipal High Income Opportunity Fund', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (191, 'First Financial Bancorp.', 'Bengali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (192, 'Super Micro Computer, Inc.', 'Malay');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (193, 'Aduro Biotech, Inc.', 'Haitian Creole');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (194, 'Biolase, Inc.', 'Danish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (195, 'Skyworks Solutions, Inc.', 'Swahili');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (196, 'HFF, Inc.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (197, 'Brown Forman Corporation', 'Māori');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (198, 'PDC Energy, Inc.', 'Hindi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (199, 'Vident Core US Equity ETF', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (200, 'Myriad Genetics, Inc.', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (201, 'Heat Biologics, Inc.', 'Tamil');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (202, 'UnitedHealth Group Incorporated', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (203, 'Hewlett Packard Enterprise Company', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (204, 'DTE Energy Company', 'Māori');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (205, 'Associated Banc-Corp', 'Malay');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (206, 'Ever-Glory International Group, Inc.', 'Italian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (207, 'First Trust Developed Markets Ex-US AlphaDEX Fund', 'Oriya');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (208, 'Alliance World Dollar Government Fund II', 'Catalan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (209, 'Sajan, Inc.', 'Swati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (210, 'ANI Pharmaceuticals, Inc.', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (211, 'OCI Partners LP', 'Hindi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (212, 'Zendesk, Inc.', 'Spanish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (213, 'Eastman Kodak Company', 'Danish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (214, 'Crescent Point Energy Corporation', 'Estonian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (215, 'Colony NorthStar, Inc.', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (216, 'RAIT Financial Trust', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (217, 'Citigroup Inc.', 'Māori');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (218, 'PIMCO New York Municipal Income Fund', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (219, 'Dawson Geophysical Company', 'Azeri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (220, 'AmTrust Financial Services, Inc.', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (221, 'Vanguard Long-Term Corporate Bond ETF', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (222, 'Wayside Technology Group, Inc.', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (223, 'The Health and Fitness ETF', 'Japanese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (224, 'Alliance Holdings GP, L.P.', 'Amharic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (225, 'Sino-Global Shipping America, Ltd.', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (226, 'Vascular Biogenics Ltd.', 'Lithuanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (227, 'BlackRock Resources', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (228, 'VelocityShares 3x Inverse Gold ETN', 'West Frisian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (229, 'United States Lime & Minerals, Inc.', 'Hindi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (230, 'Abraxas Petroleum Corporation', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (231, 'Bank of America Corporation', 'Bulgarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (232, 'SciClone Pharmaceuticals, Inc.', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (233, 'Mallinckrodt plc', 'Yiddish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (234, 'PC Connection, Inc.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (235, 'Special Opportunities Fund Inc.', 'Burmese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (236, 'Diversicare Healthcare Services Inc.', 'Macedonian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (237, 'Safe Bulkers, Inc', 'Kannada');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (238, 'Landcadia Holdings, Inc.', 'Punjabi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (239, 'Quad Graphics, Inc', 'Lao');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (240, 'Condor Hospitality Trust, Inc.', 'Azeri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (241, 'Lehman ABS Corporation', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (242, 'W.R. Berkley Corporation', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (243, 'LeMaitre Vascular, Inc.', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (244, 'Rosetta Stone', 'Tetum');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (245, 'Ameren Corporation', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (246, 'Shore Bancshares Inc', 'Amharic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (247, 'HopFed Bancorp, Inc.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (248, 'First Trust Emerging Markets Small Cap AlphaDEX Fund', 'Greek');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (249, 'ProShares UltraShort Nasdaq Biotechnology', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (250, 'ProShares UltraPro QQQ', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (251, 'Quad Graphics, Inc', 'Finnish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (252, 'Bill Barrett Corporation', 'Oriya');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (253, 'Bank of America Corporation', 'Papiamento');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (254, 'United Technologies Corporation', 'Burmese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (255, 'Torchmark Corporation', 'Persian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (256, 'Milacron Holdings Corp.', 'Czech');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (257, 'Fifth Third Bancorp', 'Malayalam');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (258, 'NeuroMetrix, Inc.', 'Lao');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (259, 'Jack In The Box Inc.', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (260, 'MUELLER WATER PRODUCTS', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (261, 'IDEX Corporation', 'Aymara');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (262, 'EastGroup Properties, Inc.', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (263, 'MYR Group, Inc.', 'Maltese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (264, 'Ericsson', 'Greek');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (265, 'Rigel Pharmaceuticals, Inc.', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (266, 'Federal Agricultural Mortgage Corporation', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (267, 'Liberty Media Corporation', 'Swati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (268, 'Capital One Financial Corporation', 'Japanese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (269, 'E.W. Scripps Company (The)', 'Catalan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (270, 'Landmark Bancorp Inc.', 'Azeri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (271, 'CONSOL Energy Inc.', 'Kyrgyz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (272, 'Cliffs Natural Resources Inc.', 'Croatian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (273, 'Gilead Sciences, Inc.', 'Chinese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (274, 'AMC Networks Inc.', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (275, 'Vince Holding Corp.', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (276, 'Fidelity National Information Services, Inc.', 'Belarusian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (277, 'MakeMyTrip Limited', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (278, 'The Obesity ETF', 'Danish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (279, 'Customers Bancorp, Inc', 'Montenegrin');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (280, 'PAVmed Inc.', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (281, 'Blackrock MuniHoldings Quality Fund, Inc.', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (282, 'Invesco Plc', 'Dutch');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (283, 'Histogenics Corporation', 'Croatian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (284, 'Actuant Corporation', 'Mongolian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (285, 'Banc of California, Inc.', 'Malagasy');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (286, 'Globant S.A.', 'Mongolian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (287, 'Tyler Technologies, Inc.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (288, 'MacroGenics, Inc.', 'Kannada');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (289, 'Treehouse Foods, Inc.', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (290, 'Invesco Plc', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (291, 'AVEO Pharmaceuticals, Inc.', 'Swati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (292, 'Pebblebrook Hotel Trust', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (293, 'KBR, Inc.', 'Tswana');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (294, 'MidSouth Bancorp', 'Māori');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (295, 'Broadridge Financial Solutions, Inc.', 'Kashmiri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (296, 'Brooks Automation, Inc.', 'Luxembourgish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (297, 'Arconic Inc.', 'Bengali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (298, 'Qwest Corporation', 'Icelandic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (299, 'The Medicines Company', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (300, 'Colonial Investment Grade Municipal Trust', 'Tswana');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (301, 'Noble Energy Inc.', 'Macedonian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (302, 'KKR Real Estate Finance Trust Inc.', 'Romanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (303, 'Liberty All-Star Growth Fund, Inc.', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (304, 'Westbury Bancorp, Inc.', 'Swati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (305, 'NxStage Medical, Inc.', 'Belarusian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (306, 'OHA Investment Corporation', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (307, 'Westmoreland Resource Partners, LP', 'West Frisian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (308, 'Lydall, Inc.', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (309, 'Delta Technology Holdings Limited', 'Bosnian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (310, 'Westlake Chemical Partners LP', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (311, 'Braskem S.A.', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (312, 'Mountain Province Diamonds Inc.', 'Gagauz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (313, 'Oramed Pharmaceuticals Inc.', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (314, 'Affimed N.V.', 'Romanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (315, 'Finjan Holdings, Inc.', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (316, 'Oconee Federal Financial Corp.', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (317, 'Insight Select Income Fund', 'Dutch');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (318, 'A10 Networks, Inc.', 'Fijian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (319, 'Altisource Residential Corporation', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (320, 'Pulmatrix, Inc.', 'Mongolian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (321, 'Axis Capital Holdings Limited', 'Bulgarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (322, 'PowerShares Optimum Yield Diversified Commodity Strategy No K-', 'Hebrew');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (323, 'StoneCastle Financial Corp', 'Tsonga');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (324, 'LHC Group', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (325, 'GasLog LP.', 'Azeri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (326, '8point3 Energy Partners LP', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (327, 'Bristow Group Inc', 'Swahili');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (328, 'Agrium Inc.', 'Estonian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (329, 'Tidewater Inc.', 'Swahili');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (330, 'Eaton Vance NextShares Trust', 'Kurdish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (331, 'Companhia de saneamento Basico Do Estado De Sao Paulo - Sabesp', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (332, 'Adtalem Global Education Inc.', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (333, 'Insperity, Inc.', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (334, 'PIMCO Income Strategy Fund II', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (335, 'Arconic Inc.', 'Maltese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (336, 'VictoryShares US Discovery Enhanced Volatility Wtd ETF', 'Gagauz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (337, 'Magna International, Inc.', 'Somali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (338, 'Vermillion, Inc.', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (339, 'Advanced Energy Industries, Inc.', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (340, 'Premier Financial Bancorp, Inc.', 'Croatian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (341, 'iPath US Treasury 5-year Bull ETN', 'Kannada');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (342, 'Lear Corporation', 'Gagauz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (343, 'Tocagen Inc.', 'Fijian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (344, 'FNB Bancorp', 'Armenian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (345, 'Himax Technologies, Inc.', 'Spanish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (346, 'iPath US Treasury 2-year Bear ETN', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (347, 'Gladstone Land Corporation', 'Mongolian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (348, 'DTE Energy Company', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (349, 'Wells Fargo Global Dividend Opportunity Fund', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (350, 'Allstate Corporation (The)', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (351, 'Prudential Global Short Duration High Yield Fund, Inc.', 'Oriya');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (352, 'Gabelli Multi-Media Trust Inc. (The)', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (353, 'Pool Corporation', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (354, 'Vantage Energy Acquisition Corp.', 'Papiamento');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (355, 'Ubiquiti Networks, Inc.', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (356, 'MakeMyTrip Limited', 'Maltese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (357, 'Mazor Robotics Ltd.', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (358, 'CBIZ, Inc.', 'Czech');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (359, 'Xerox Corporation', 'Swahili');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (360, 'Orix Corp Ads', 'English');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (361, 'Cooper-Standard Holdings Inc.', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (362, 'Stock Yards Bancorp, Inc.', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (363, 'PPlus Trust', 'Kashmiri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (364, 'World Point Terminals, LP', 'Punjabi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (365, 'Yatra Online, Inc.', 'Bengali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (366, 'Kimco Realty Corporation', 'Polish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (367, 'uniQure N.V.', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (368, 'Pebblebrook Hotel Trust', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (369, 'Interlink Electronics, Inc.', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (370, 'ArQule, Inc.', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (371, 'Nuveen New York Municipal Value Fund, Inc.', 'Persian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (372, 'Five Point Holdings, LLC', 'Spanish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (373, 'Centennial Resource Development, Inc.', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (374, 'Banner Corporation', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (375, 'Duke Energy Corporation', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (376, 'Endurance Specialty Holdings Ltd', 'Tetum');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (377, 'Leaf Group Ltd.', 'Icelandic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (378, 'Flowers Foods, Inc.', 'Swedish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (379, 'First Commonwealth Financial Corporation', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (380, 'Natural Alternatives International, Inc.', 'Croatian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (381, 'GCP Applied Technologies Inc.', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (382, 'Hunter Maritime Acquisition Corp.', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (383, 'Obalon Therapeutics, Inc.', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (384, 'iPath US Treasury 2-year Bear ETN', 'Finnish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (385, 'Daily Journal Corp. (S.C.)', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (386, 'Duff & Phelps Utilities Tax-Free Income, Inc.', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (387, 'Trinity Industries, Inc.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (388, 'Allegiant Travel Company', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (389, 'iShares MSCI Europe Small-Cap ETF', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (390, 'Commerce Union Bancshares, Inc.', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (391, 'Jazz Pharmaceuticals plc', 'Kazakh');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (392, 'DaVita Inc.', 'Bengali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (393, 'Lions Gate Entertainment Corporation', 'Italian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (394, 'Aspen Technology, Inc.', 'Dutch');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (395, 'Euronav NV', 'Icelandic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (396, 'Kingsway Financial Services, Inc.', 'Kazakh');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (397, 'Forest City Realty Trust, Inc.', 'Luxembourgish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (398, 'PartnerRe Ltd.', 'Bosnian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (399, 'Archrock Partners, L.P.', 'Haitian Creole');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (400, 'RiverNorth Opportunities Fund, Inc.', 'Catalan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (401, 'GenVec, Inc.', 'Portuguese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (402, 'Ohr Pharmaceuticals, Inc.', 'Catalan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (403, 'Liberty Media Corporation', 'Irish Gaelic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (404, 'Capital One Financial Corporation', 'Luxembourgish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (405, 'Gogo Inc.', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (406, 'Radcom Ltd.', 'Irish Gaelic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (407, 'Esperion Therapeutics, Inc.', 'Polish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (408, 'ClearBridge All Cap Growth ETF', 'Catalan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (409, 'John B. Sanfilippo & Son, Inc.', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (410, 'Enable Midstream Partners, LP', 'Hindi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (411, 'Pure Storage, Inc. ', 'Bosnian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (412, 'Fair Isaac Corporation', 'Korean');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (413, 'MoSys, Inc.', 'Azeri');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (414, 'PowerShares S&P SmallCap Materials Portfolio', 'Finnish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (415, 'Andina Acquisition Corp. II', 'Kyrgyz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (416, 'CPB Inc.', 'West Frisian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (417, 'ImmuCell Corporation', 'Assamese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (418, 'B&G Foods, Inc.', 'Romanian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (419, 'Oxford Lane Capital Corp.', 'Gagauz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (420, 'Forum Merger Corporation', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (421, 'NeoGenomics, Inc.', 'Amharic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (422, 'China Southern Airlines Company Limited', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (423, 'West Bancorporation', 'Tswana');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (424, 'AirMedia Group Inc', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (425, 'AutoZone, Inc.', 'Norwegian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (426, 'Washington Trust Bancorp, Inc.', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (427, 'Ashford Hospitality Trust Inc', 'Bulgarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (428, 'Genuine Parts Company', 'Khmer');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (429, 'Boot Barn Holdings, Inc.', 'Dari');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (430, 'ICON plc', 'Malay');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (431, 'R.R. Donnelley & Sons Company', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (432, 'Office Depot, Inc.', 'Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (433, 'Finjan Holdings, Inc.', 'Persian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (434, 'AU Optronics Corp', 'New Zealand Sign Language');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (435, 'LogMein, Inc.', 'Amharic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (436, 'Marlin Business Services Corp.', 'Nepali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (437, 'CBRE Clarion Global Real Estate Income Fund', 'Northern Sotho');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (438, 'ProAssurance Corporation', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (439, 'Wins Finance Holdings Inc.', 'Malay');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (440, 'East West Bancorp, Inc.', 'Japanese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (441, 'Watsco, Inc.', 'Pashto');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (442, 'Cross Timbers Royalty Trust', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (443, 'Veritone, Inc.', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (444, 'BMC Stock Holdings, Inc.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (445, 'Medical Properties Trust, Inc.', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (446, 'Goldman Sachs Group, Inc. (The)', 'Dhivehi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (447, 'FibroGen, Inc', 'Maltese');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (448, 'Newtek Business Services Corp.', 'Haitian Creole');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (449, 'Liberty Global plc', 'Macedonian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (450, 'Northeast Bancorp', 'Khmer');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (451, 'ClearBridge Dividend Strategy ESG ETF', 'Thai');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (452, 'RELX N.V.', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (453, 'Coeur Mining, Inc.', 'Malayalam');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (454, 'Insmed, Inc.', 'Dzongkha');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (455, 'Apple Inc.', 'Aymara');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (456, 'Axis Capital Holdings Limited', 'Norwegian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (457, 'RADA Electronic Industries Ltd.', 'Malay');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (458, 'iShares Morningstar Mid-Cap ETF', 'Somali');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (459, 'Catalyst Pharmaceuticals, Inc.', 'Fijian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (460, 'Banco Bilbao Viscaya Argentaria S.A.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (461, 'LaSalle Hotel Properties', 'Korean');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (462, 'BlackRock, Inc.', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (463, 'Sensus Healthcare, Inc.', 'Ndebele');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (464, 'O''Reilly Automotive, Inc.', 'Khmer');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (465, 'Perceptron, Inc.', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (466, 'Visa Inc.', 'Greek');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (467, 'Kenon Holdings Ltd.', 'Luxembourgish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (468, 'Lamar Advertising Company', 'Tetum');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (469, 'Saban Capital Acquisition Corp.', 'Belarusian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (470, 'Kingtone Wirelessinfo Solution Holding Ltd', 'Lao');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (471, 'Southern California Edison Company', 'Tajik');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (472, 'Era Group, Inc.', 'Ndebele');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (473, 'Galena Biopharma, Inc.', 'Dari');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (474, 'Vanguard Russell 2000 Value ETF', 'Malagasy');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (475, 'Qorvo, Inc.', 'Afrikaans');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (476, 'Origin Agritech Limited', 'Polish');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (477, 'Nuance Communications, Inc.', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (478, 'Pennsylvania Real Estate Investment Trust', 'German');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (479, 'Mellanox Technologies, Ltd.', 'Marathi');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (480, 'Resource Capital Corp.', 'Korean');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (481, 'LSI Industries Inc.', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (482, 'Invesco Mortgage Capital Inc.', 'Czech');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (483, 'Flowers Foods, Inc.', 'Oriya');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (484, 'Golar LNG Partners LP', 'Hungarian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (485, 'Wesco Aircraft Holdings, Inc.', 'Greek');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (486, 'Five Below, Inc.', 'Persian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (487, 'Qiagen N.V.', 'Arabic');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (488, 'Ritter Pharmaceuticals, Inc.', 'Georgian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (489, 'Social Reality, Inc.', 'Zulu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (490, 'Tekla Life Sciences Investors', 'Telugu');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (491, 'Superior Energy Services, Inc.', 'Filipino');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (492, 'AAON, Inc.', 'Latvian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (493, 'Community Bankers Trust Corporation.', 'Belarusian');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (494, 'Gencor Industries Inc.', 'Gujarati');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (495, 'Bank of South Carolina Corp.', 'Korean');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (496, 'Energizer Holdings, Inc.', 'Moldovan');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (497, 'ZAIS Group Holdings, Inc.', 'Gagauz');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (498, 'BRF S.A.', 'English');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (499, 'Woodward, Inc.', 'Bislama');
insert into catalogo.LIBRO (ISBN, TITULO, IDIOMA) values (500, 'WPX Energy, Inc.', 'Nepali');
